### ISSUE TITLE
Outdated code version

### ISSUE THREAD

**Issue by asiekierka** [chee/libntxm#1]
https://code.google.com/archive/p/libntxm/source/default/source provides a newer version of the code, with FIFO commands as opposed to hard-coded IPC locations.

**Comment by chee** [comment]
ooh, thank you!!! give me a moment

**Comment by asiekierka** [comment]
(This is mostly of interest to me as 0xtob's upload seems to be forked off yours, and I want to contribute to it in order to add fixes for DSi/3DS support.)

**Comment by chee** [comment]
@asiekierka i've updated it here, but i think 0xtob will need to update it over there too. i'm happy to take the fixes on this repo though!!

**Comment by asiekierka** [comment]
A mistake has been made - some files (command7.cpp, command9.cpp, etc.) were deleted in the latest version of the source code, but remain here.

I've already PR'd the NitroTracker part of the fixes to 0xtob; I'll see how he responds.

**Comment by chee** [comment]
@asiekierka oh yeah, quite true. i'll update
